### ISSUE TITLE
朋友 ～你好

### ISSUE THREAD

**Issue by ghost** [nanolikeyou/jniwebshell#2]
发现您fork了我的工程 std-repository
公司目前扫描发现有些资料不方便对外公开，需要帮忙删除。
能否删除这个fork的库？https://github.com/nanolikeyou/std-repository
目前新的库是这个：https://github.com/CyC2018/CS-Notes 欢迎fork并贡献代码。

**Comment by BigStupideer** [comment]
发现您fork了我的工程 std-repository
公司目前扫描发现有些资料不方便对外公开，需要帮忙删除。
能否删除这个fork的库？https://github.com/nanolikeyou/std-repository
目前新的库是这个：https://github.com/CyC2018/CS-Notes 欢迎fork并贡献代码。
